In [1]:
import os

directory_list = []
for root, dirs, files in os.walk("/Users/ibergeland/Downloads/step_counts/", topdown=False):
    for name in dirs:
        directory_list.append(os.path.join(root, name))

import glob
import pandas as pd

step_count=pd.DataFrame()
filenames=pd.DataFrame()
str='/*.xls'
paths=[x+str for x in directory_list]
paths.sort()

In [2]:
for path in paths:
    filenames = glob.glob(path)
    for filename in filenames:
        df=pd.read_excel(filename, sheet_name='Activities')
        df['studyID']=path[46:50]
        step_count=step_count.append(df)
step_count=step_count.set_index('studyID')
step_count

,Date,Calories Burned,Steps,Distance,Floors,Minutes Sedentary,Minutes Lightly Active,Minutes Fairly Active,Minutes Very Active,Activity Calories
studyID,,,,,,,,,,
2001,2015-07-23,"2,902","9,865",4.55,0.0,"1,234",194.0,2.0,10,"1,170"
2001,2015-07-24,"2,637","6,695",3.12,0.0,"1,267",164.0,7.0,2,875
2001,2015-07-25,"2,508","5,311",2.44,0.0,"1,300",140.0,0.0,0,696
2001,2015-07-26,"2,222","2,176",1.00,0.0,"1,368",72.0,0.0,0,327
2001,2015-07-27,"3,491","16,141",10.72,0.0,"1,265",75.0,11.0,89,"1,721"
2001,2015-07-28,"3,654","17,842",12.25,0.0,"1,166",184.0,21.0,69,"2,038"
2001,2015-07-29,"2,472","4,471",2.07,0.0,"1,299",141.0,0.0,0,648
2001,2015-07-30,"2,373","3,482",1.63,0.0,"1,334",106.0,0.0,0,500
2001,2015-07-31,"4,127","23,967",11.01,0.0,924,400.0,90.0,26,"2,829"
2001,2015-08-01,"2,096","1,224",0.56,0.0,"1,416",13.0,9.0,2,134
2001,2015-08-02,"2,489","4,832",2.31,0.0,"1,327",99.0,3.0,11,625
2001,2015-08-03,"1,994",0,0.00,0.0,"1,440",0.0,0.0,0,0
2001,2015-08-04,"2,263","2,713",1.25,0.0,"1,363",70.0,7.0,0,373
2001,2015-08-05,"2,981","16,479",9.11,0.0,"1,272",109.0,8.0,51,"1,221"
2001,2015-08-06,"2,157","1,507",0.69,0.0,"1,388",52.0,0.0,0,233
2001,2015-08-07,"2,821","7,928",3.64,0.0,"1,213",205.0,8.0,14,"1,117"
2001,2015-08-08,"1,997",7,0.00,0.0,"1,439",1.0,0.0,0,4
2001,2015-08-09,"2,425","3,603",1.66,0.0,"1,289",142.0,8.0,1,640
2001,2015-08-10,"2,138","1,188",0.55,0.0,"1,390",50.0,0.0,0,211
2001,2015-08-11,"3,665","17,616",11.97,0.0,"1,127",219.0,27.0,67,"2,050"
2001,2015-08-12,"2,369","3,124",1.49,0.0,"1,334",94.0,11.0,1,481
2001,2015-08-13,"2,528","4,726",2.19,0.0,"1,306",108.0,12.0,14,665
2001,2015-08-14,"2,456","3,743",1.80,0.0,"1,374",39.0,8.0,19,427
2001,2015-08-15,"1,994",0,0.00,0.0,"1,440",0.0,0.0,0,0
2001,2015-08-16,"2,585","6,543",3.03,0.0,"1,297",117.0,17.0,9,781
2001,2015-08-17,"2,182","1,611",0.74,0.0,"1,386",54.0,0.0,0,247
2001,2015-08-18,"1,997",18,0.01,0.0,"1,439",1.0,0.0,0,4
2001,2015-08-19,"2,118","1,067",0.49,0.0,"1,397",43.0,0.0,0,183
2001,2015-08-20,"2,966","11,010",9.19,0.0,"1,292",73.0,22.0,53,"1,158"
2001,2015-08-21,"2,949","10,661",18.72,0.0,"1,334",35.0,5.0,66,"1,104"
...,...,...,...,...,...,...,...,...,...,...
2085,2016-01-09,"2,064","7,996",3.64,0.0,"1,208",203.0,8.0,21,837
2085,2016-01-10,"3,661","32,943",16.63,0.0,"1,023",222.0,29.0,166,"2,622"
2085,2016-01-11,"2,025","8,127",3.61,0.0,"1,236",162.0,8.0,34,792
2085,2016-01-12,"2,189","10,401",4.78,0.0,"1,206",196.0,5.0,33,962
2085,2016-01-13,"2,330","13,278",5.80,0.0,"1,162",207.0,30.0,41,"1,155"
2085,2016-01-14,"2,164","9,804",4.34,0.0,"1,154",261.0,15.0,10,"1,008"
2085,2016-01-15,"1,824","4,820",2.06,0.0,"1,283",148.0,4.0,5,525
2085,2016-01-16,"1,839","4,397",1.87,0.0,"1,243",197.0,0.0,0,592
2085,2016-01-17,"2,064","7,882",3.36,0.0,"1,172",248.0,10.0,10,893
2085,2016-01-18,"2,480","14,420",6.80,0.0,"1,138",222.0,17.0,63,"1,312"
2085,2016-01-19,"2,176","9,165",4.16,0.0,"1,174",246.0,9.0,11,952
2085,2016-01-20,"2,092","9,173",4.31,0.0,"1,253",154.0,5.0,28,822
2085,2016-01-21,"2,209","10,390",4.86,0.0,"1,206",185.0,13.0,36,970
2085,2016-01-22,"2,474","14,497",6.77,0.0,"1,147",210.0,21.0,62,"1,292"
2085,2016-01-23,"2,161","8,552",3.64,0.0,"1,135",282.0,11.0,12,994
2085,2016-01-24,"2,239","10,988",4.91,0.0,"1,184",193.0,20.0,43,"1,030"
2085,2016-01-25,"2,786","18,149",8.99,0.0,"1,107",230.0,20.0,83,"1,611"
2085,2016-01-26,"2,132","9,556",4.52,0.0,"1,214",179.0,11.0,36,920
2085,2016-01-27,"2,600","17,229",8.02,0.0,"1,126",222.0,26.0,66,"1,461"
2085,2016-01-28,"2,219","10,068",4.73,0.0,"1,163",237.0,7.0,33,"1,047"
2085,2016-01-29,"1,815","4,372",1.86,0.0,"1,269",162.0,8.0,1,539
2085,2016-01-30,"2,666","18,662",8.11,0.0,"1,032",319.0,49.0,40,"1,636"
2085,2016-01-31,"2,096","9,148",4.06,0.0,"1,230",147.0,25.0,38,854
2085,2016-02-01,"2,267","11,212",5.30,0.0,"1,164",238.0,6.0,32,"1,102"
2085,2016-02-02,"2,552","15,332",7.20,0.0,"1,086",307.0,8.0,39,"1,465"
2085,2016-02-03,"2,747","19,767",9.08,0.0,"1,097",235.0,20.0,88,"1,643"
2085,2016-02-04,"2,469","14,939",6.43,0.0,"1,098",291.0,7.0,44,"1,367"
2085,2016-02-05,"2,466","14,995",6.96,0.0,"1,178",192.0,12.0,58,"1,243"
2085,2016-02-06,"2,257","9,854",4.19,0.0,"1,126",292.0,13.0,9,"1,079"
2085,2016-02-07,"1,849","3,932",1.67,0.0,"1,240",200.0,0.0,0,585